name: practice
on: [push]
jobs:
  version_control_repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
  use_reusable:
    needs: version_control_repo
    uses: ./.github/workflows/reusable.yml
